Fix ExperimentalSpreadProperty causing errors (#13)
Without this, if you had a object like this:

    var a = {}
    var b = { ...a };

It would throw an error:

    Cannot read property 'type' of undefined
    TypeError: Cannot read property 'type' of undefined
        at .../eslint-plugin-sorting/index.js:19:37
        at Array.reduce (native)
        at EventEmitter.ObjectExpression (.../eslint-plugin-sorting/index.js:13:37)

This fixes it. By ignoring the ExperimentalSpreadProperty altogether.